FROM ubuntu:14.04env as builder

MAINTAINER Yuan Sun sunyuan3@huawei.com

WORKDIR /root

RUN git clone https://github.com/sunyuan3/netperf.git \
	&& cd netperf \
	&& ./configure \
	&& make && make install

CMD ["/bin/sh", "-c", "/usr/local/bin/netserver"]

FROM ubuntu:14.04
COPY --from=builder /usr/local/bin/netserver /usr/local/bin/
CMD ["/bin/sh", "-c", "/usr/local/bin/netserver"]
